name: Run pipeline inside docker
on:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  container_build:
    runs-on: ubuntu-latest
    container:
      image: sage/azure-ansible-github-runner:4efc83f
      credentials:
        username: ${{ vars.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        registry: sagecentralhubacr.azurecr.io
    steps:
      - run: echo "Running 1.2.0"
      - run: cat /etc/os-release
    